Repository DeveloperAcademy-POSTECH/MacC-Team-SecretAgent, pull requests merged in 2022-12, with the labels that each got.

#46 [FEAT] 요원 선택 결과 화면 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Ex/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Ex/agentCardEx.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Ex/agentCardEx.imageset/agentCardEx.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/primaryButtonBackground.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/primaryButtonBackground.imageset/primaryButtonBackground.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/yohanKo.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/yohanKo.imageset/yohanKo.pdf
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentCardIssuanceViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentSelectionCompleteViewController.swift
Labels: 🏞 UI, ❤️ Woogy

#49 [FEAT] 구구단뷰 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Cell/NumberCollectionViewCell.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/CalculatorResultView.swift
Labels: 🏞 UI, 🌊 Miller

#52 [ADD] Aftertimerview 구현 및 타이머 연결
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/timerFail.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/timerFail.imageset/timerFail.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/timerSuccess.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/timerSuccess.imageset/timerSuccess.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/timerTimeOut.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/timerTimeOut.imageset/timerTimeOut.svg
  SecretAgent/SecretAgent/Global/Resource/Base.lproj/Main.storyboard
  SecretAgent/SecretAgent/Screen/Siren/AfterTimerDetailViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/AfterTimerViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
Labels: 🏞 UI, 🌊 Miller

#55 [ADD] 요원증 뷰
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/UIFont+Extension.swift
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Biyo-Circle-Profile.imageset/CharProfile-Biyo-Circle-Profile.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Biyo-Circle-Profile.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Kiyo-Circle-Profile.imageset/CharProfile-Kiyo-Circle-Profile.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Kiyo-Circle-Profile.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Mayo-Circle-Profile.imageset/CharProfile-Mayo-Circle-Profile.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Mayo-Circle-Profile.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Poyo-Circle-Profile.imageset/CharProfile-Poyo-Circle-Profile.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/CharProfile-Poyo-Circle-Profile.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/CircleProfile/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/agentCard.background.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/agentCard.background.imageset/agentCard.background.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.small.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.small.imageset/coin.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.stroke.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.stroke.imageset/coin.stroke.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/divider.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/divider.imageset/divider.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/ggoyos.logo.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/ggoyos.logo.imageset/ggoyos.logo.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/poyo.circle.profile.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/poyo.circle.profile.imageset/poyo.circle.profile.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/x.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/x.imageset/x.svg
  SecretAgent/SecretAgent/Screen/AgentCard/AgentCardViewController.swift
  SecretAgent/SecretAgent/Screen/AgentCard/View/AgentCardView.swift
  SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
  SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
  SecretAgent/SecretAgent/Screen/Main/View/Component/AgentCardThumbnail.swift
  SecretAgent/SecretAgent/Screen/Main/View/Component/TodayBadge.swift
Labels: 🤖 Cozy, 🏞 UI

#56 [FEAT] 보드 뷰 UI 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.all.active.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.all.active.imageset/star.all.active.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.all.inactive.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.all.inactive.imageset/star.all.inactive.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.biyo.active.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.biyo.active.imageset/star.biyo.active.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.biyo.inactive.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.biyo.inactive.imageset/star.biyo.inactive.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.kiyo.active.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.kiyo.active.imageset/star.kiyo.active.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.kiyo.inactive.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.kiyo.inactive.imageset/star.kiyo.inactive.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.mayo.active.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.mayo.active.imageset/star.mayo.active.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.mayo.inactive.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.mayo.inactive.imageset/star.mayo.inactive.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.poyo.active.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.poyo.active.imageset/star.poyo.active.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.poyo.inactive.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.poyo.inactive.imageset/star.poyo.inactive.svg
  SecretAgent/SecretAgent/Screen/Board/View/BadgeCollectionViewCell.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
  SecretAgent/SecretAgent/Screen/Board/View/CommonBadgeInfoComponent.swift
  SecretAgent/SecretAgent/Screen/Board/View/HideBadgeView.swift
Labels: 🎻 Dani, 🏞 UI

#61 [ADD] 오픈소스 라이선스 뷰 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Screen/Main/OpenSourceViewController.swift
Labels: 🏞 UI, 🌊 Miller

#66 [FEAT] 사이렌 알림 기능 추가
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
Labels: 🌊 Miller

#68 [Feat] siren 뱃지 감소 코어데이터 기능 추가
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Screen/Siren/AfterTimerDetailViewController.swift
Labels: Ꜣ Logic, 🌊 Miller

#75 [FEAT] 사이렌 사운드 구현
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
Labels: Ꜣ Logic, 🌊 Miller

#77 [UI] 이미지 최신화 및 폰트 적용
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Scenes/Scene10.imageset/Scene10.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Scenes/Scene9.imageset/Scene9.pdf
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene5.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene7.mp3
  SecretAgent/SecretAgent/Global/UIComponent/BaseButton.swift
  SecretAgent/SecretAgent/Screen/AgentSelection/AgentSelectionViewController.swift
  SecretAgent/SecretAgent/Screen/Story/StoryViewController .swift
Labels: 🏞 UI, ❤️ Woogy

#84 [FIX] Siren QA resolved
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
Labels: 🏞 UI, 🌊 Miller

#86 [ADD] 스토리뷰, 메인탭뷰 연결 구현
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentCardIssuanceViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentSelectionCompleteViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelection/AgentSelectionViewController.swift
  SecretAgent/SecretAgent/Screen/Story/StoryViewController .swift
Labels: 🏞 UI, 🌊 Miller

#89 [FEAT, FIX] 뱃지 얻었을 때 동작 구현, QA 반영
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/allStarCompleted.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/allStarCompleted.imageset/allStarCompleted.png
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/allStarCompletedTransparent.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/allStarCompletedTransparent.imageset/allStarCompletedTransparent.png
  SecretAgent/SecretAgent/Global/Resource/Base.lproj/Main.storyboard
  SecretAgent/SecretAgent/Global/Service/BadgeManager.swift
  SecretAgent/SecretAgent/Model/Badge.swift
  SecretAgent/SecretAgent/Screen/Board/View/BadgeCollectionViewCell.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController+Extension.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
  SecretAgent/SecretAgent/Screen/Board/View/StarCollectCongratsViewController.swift
Labels: 🐞 Bug, 🎻 Dani, Ꜣ Logic

#88 [REFACT] 잠금해제뷰 레이아웃 비율로 수정
  SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
  SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
Labels: 🛠 Refactoring, 🌊 Miller

#90 [ADD] 요원 정보 User Default 연동
  SecretAgent/SecretAgent/Global/UIComponent/BaseButton.swift
  SecretAgent/SecretAgent/Screen/AgentCard/View/AgentCardView.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentCardIssuanceViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentSelectionCompleteViewController.swift
  SecretAgent/SecretAgent/Screen/Board/View/Components/TodayCoinModal.swift
  SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
  SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
Labels: 🤖 Cozy, 🏞 UI

#91 [ADD] 자잘한 디테일 적용
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/yohanKo.imageset/yohanKo.pdf
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Model/Guide.swift
  SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
  SecretAgent/SecretAgent/Screen/Main/OpenSourceViewController.swift
  SecretAgent/SecretAgent/Screen/OnBoarding/OnBoardingViewController.swift
  SecretAgent/SecretAgent/Screen/Story/StoryViewController .swift
  SecretAgent/SecretAgent/Screen/StoryTab/StoryTabViewController.swift
  SecretAgent/SecretAgent/Screen/StoryTab/View/StoryCell.swift
Labels: 🏞 UI, ❤️ Woogy

#93 [FIX] 사이렌 타이머 자동 실행
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
Labels: Ꜣ Logic, 🌊 Miller

#94 [FEAT, FIX] 코인, 스타 획득 사운드 추가 및 버그 해결
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
  SecretAgent/SecretAgent/Screen/Board/View/StarCollectCongratsViewController.swift
Labels: 🎻 Dani, Ꜣ Logic, 🏞 UI

#96 [FEAT, FIX] 무음모드 시에도 소리 실행되게, 버그 수정
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Service/SoundManager.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
Labels: 🐞 Bug, 🎻 Dani, Ꜣ Logic

#95 [FIX] unlock뷰 resultview 레이아웃 조정
  SecretAgent/SecretAgent/Screen/Siren/View/Component/CalculatorResultView.swift
Labels: 🏞 UI, 🌊 Miller

#98 [ADD] Scene5 이미지 수정
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Scenes/Scene5.imageset/Scene5.pdf
Labels: 🏞 UI, 🌊 Miller

#92 [CHORE] 작은 디테일 수정
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/speechImage.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/speechImage.imageset/speechImage.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/speechImage.imageset/speechImage.svg
  SecretAgent/SecretAgent/Global/Support/AppDelegate.swift
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Global/UIComponent/BaseButton.swift
  SecretAgent/SecretAgent/Model/Story.swift
  SecretAgent/SecretAgent/Screen/AgentCard/AgentCardViewController.swift
  SecretAgent/SecretAgent/Screen/AgentCard/View/AgentCardView.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentCardIssuanceViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentSelectionCompleteViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelection/AgentSelectionViewController.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController+Extension.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
  SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
  SecretAgent/SecretAgent/Screen/OnBoarding/OnBoardingViewController.swift
  SecretAgent/SecretAgent/Screen/Story/StoryViewController .swift
Labels: 🏞 UI, ❤️ Woogy

#99 [ADD] 타이머 30초 남으면 대화말 변경
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/speechImage2.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Timer/speechImage2.imageset/speechImage2.svg
  SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
Labels: 🏞 UI, 🌊 Miller

#100 [FEAT] 7시 이후 첫 방문에만 정산하는 기능 구현
  SecretAgent/SecretAgent/Global/Service/BadgeManager.swift
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
Labels: 🎻 Dani, Ꜣ Logic, ❤️ Woogy

#101 [FIX] 타이머 자동 재생 및 애니메이션 프로그래스바 유지
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
Labels: 🐞 Bug, 🤖 Cozy, 🌊 Miller

#106 [UI] 요원 선택, 결과, 첫 요원증 화면 버튼 글자색 검정색 설정
  SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
  SecretAgent/SecretAgent/Global/Service/SoundManager.swift
  SecretAgent/SecretAgent/Global/Support/AppDelegate.swift
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentCardIssuanceViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelectComplete/AgentSelectionCompleteViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelection/AgentSelectionViewController.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
  SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
  SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
Labels: 🏞 UI, ❤️ Woogy

#104 [Fix] Unlockview layout
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/CalculatorResultView.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
Labels: 🐞 Bug, 🌊 Miller

#113 [FIX] 타이머 버그 수정
  SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
Labels: 🐞 Bug, 🌊 Miller
