Repository DeveloperAcademy-POSTECH/MacC-Team-SecretAgent, pull requests merged in 2022-11, with the labels that each got.

#2 [FEAT] SwiftFormat을 추가하였습니다.
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/.swiftformat
  SecretAgent/SecretAgent/Global/Base/BaseCollectionViewCell.swift
  SecretAgent/SecretAgent/Global/Base/BaseTableViewCell.swift
  SecretAgent/SecretAgent/Global/Base/BaseViewController.swift
  SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/NSObject+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/UICollectionView+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/UIFont+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/UITableView+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/UIViewController+Alert.swift
  SecretAgent/SecretAgent/Global/Extension/UIViewController+Extension.swift
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Support/AppDelegate.swift
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Screen/Main/ViewController.swift
  SecretAgent/SecretAgentTests/SecretAgentTests.swift
  SecretAgent/SecretAgentUITests/SecretAgentUITests.swift
  SecretAgent/SecretAgentUITests/SecretAgentUITestsLaunchTests.swift
Labels: 🤖 Cozy

#6 [ADD] Github Actions: Check Build & SwiftLint
  .github/workflows/pre-pull-request.yml
  SecretAgent/SecretAgent/Global/Support/AppDelegate.swift
  SecretAgent/SecretAgent/Screen/Main/ViewController.swift
  SecretAgent/SecretAgentTests/SecretAgentTests.swift
  SecretAgent/SecretAgentUITests/SecretAgentUITests.swift
Labels: 🤖 Cozy, Ꜣ Logic

#10 [FIX] Switformat autocorrect to lint temporary
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
Labels: 🐞 Bug, 🤖 Cozy

#11 [FEAT] 타이머 기능 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Resource/Base.lproj/Main.storyboard
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
Labels: Ꜣ Logic, 🌊 Miller

#18 [FEAT] 사이렌 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/SoundLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Base.lproj/Main.storyboard
  SecretAgent/SecretAgent/Global/Resource/Sound/siren.mp3
  SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
Labels: 🎻 Dani, Ꜣ Logic

#13 [FIX] 타이머가 끝나고 다음에 start 를 누를때 애니메이션이 채워지지 않는 버그
  SecretAgent/SecretAgent/Global/Resource/Base.lproj/Main.storyboard
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
  SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
  SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
  SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
Labels: 🐞 Bug, Ꜣ Logic, 🌊 Miller

#16 [FEAT] Init UserNotificationManager
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
Labels: 🤖 Cozy, Ꜣ Logic

#17 [ADD] Core Data CRUD 기본 코드 작성
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Service/BadgeManager.swift
  SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
  SecretAgent/SecretAgent/Global/Service/Storage/SecretAgent.xcdatamodeld/SecretAgent.xcdatamodel/contents
  SecretAgent/SecretAgent/Global/Support/AppDelegate.swift
  SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
Labels: 🎻 Dani, Ꜣ Logic, ❤️ Woogy

#25 [ADD] 뱃지 보드 레이아웃 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Base.lproj/Main.storyboard
  SecretAgent/SecretAgent/Screen/Board/View/BadgeCollectionViewCell.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
Labels: 🎻 Dani, 🏞 UI

#28 [ADD]: 이미지 에셋 추가 #27
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/agent.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/agent.imageset/agent.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.activate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.activate.imageset/coin.activate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.deactivate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.deactivate.imageset/coin.deactivate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/shield.activate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/shield.activate.imageset/shield.activate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/shield.deavtivate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/shield.deavtivate.imageset/shield.deavtivate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/siren.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/siren.imageset/siren.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.activate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.activate.imageset/star.activate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.deactivate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.deactivate.imageset/star.deactivate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/story.activate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/story.activate.imageset/story.activate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/story.deactivate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/story.deactivate.imageset/story.deactivate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/woongwoong.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/woongwoong.imageset/woongwoong.png
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
Labels: 🤖 Cozy

#32 [FEAT] 메인 탭 뷰 인터페이스 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/Preview+Extension.swift
  SecretAgent/SecretAgent/Global/Extension/UIFont+Extension.swift
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.stroke.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.stroke.imageset/coin.stroke.svg
  SecretAgent/SecretAgent/Global/Resource/Base.lproj/Main.storyboard
  SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
  SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
  SecretAgent/SecretAgent/Screen/Main/View/Component/AgentCardThumbnail.swift
  SecretAgent/SecretAgent/Screen/Main/View/Component/TodayBadge.swift
Labels: 🤖 Cozy, 🏞 UI

#33 [UI] 요원 선택 뷰 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Biyo.imageset/CharProfile-Biyo.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Biyo.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Kiyo.imageset/CharProfile-Kiyo.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Kiyo.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Mayo.imageset/CharProfile-Mayo.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Mayo.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Poyo.imageset/CharProfile-Poyo.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/CharProfile-Poyo.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Basic/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Biyo-Disabled.imageset/CharProfile-Biyo-Disabled.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Biyo-Disabled.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Kiyo-Disabled.imageset/CharProfile-Kiyo-Disabled.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Kiyo-Disabled.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Mayo-Disabled.imageset/CharProfile-Mayo-Disabled.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Mayo-Disabled.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Poyo-Disabled.imageset/CharProfile-Poyo-Disabled.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/CharProfile-Poyo-Disabled.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Disabled/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Biyo-Selected.imageset/CharProfile-Biyo-Selected.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Biyo-Selected.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Kiyo-Selected.imageset/CharProfile-Kiyo-Selected.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Kiyo-Selected.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Mayo-Selected.imageset/CharProfile-Mayo-Selected.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Mayo-Selected.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Poyo-Selected.imageset/CharProfile-Poyo-Selected.pdf
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/CharProfile-Poyo-Selected.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/Agents/Selected/Contents.json
  SecretAgent/SecretAgent/Global/UIComponent/BaseButton.swift
  SecretAgent/SecretAgent/Model/Agent.swift
  SecretAgent/SecretAgent/Screen/AgentSelection/AgentSelectionViewController.swift
  SecretAgent/SecretAgent/Screen/AgentSelection/View/Cell/AgentStackViewCell.swift
Labels: Ꜣ Logic, 🧬 Model, 🏞 UI, ❤️ Woogy

#39 [FEAT] 보드 뷰 드롭다운 메뉴 및 로직 구현
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.activate.imageset/coin.activate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/shield.activate.imageset/shield.activate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/shield.deactivate.imageset/Contents.json
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/shield.deactivate.imageset/shield.deavtivate.svg
  SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/star.activate.imageset/star.activate.svg
  SecretAgent/SecretAgent/Screen/Board/View/BadgeCollectionViewCell.swift
  SecretAgent/SecretAgent/Screen/Board/View/BoardViewController.swift
  SecretAgent/SecretAgent/Screen/Board/View/HideBadgeView.swift
Labels: 🎻 Dani, Ꜣ Logic, 🏞 UI

#57 [FEAT] 사운드매니저 구현 [급]
  SecretAgent/SecretAgent.xcodeproj/project.pbxproj
  SecretAgent/SecretAgent/Global/Literal/SoundLiteral.swift
  SecretAgent/SecretAgent/Global/Resource/Sound/Badge/coinCheck.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Badge/starBadgeGain.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/OnBoarding/agentCard.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/OnBoarding/character.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/OnBoarding/choiceLikeGoOut.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Siren/failure.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Siren/siren.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Siren/success.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene1.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene2.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene3.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene4.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene5.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene6.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/Story/scene7.mp3
  SecretAgent/SecretAgent/Global/Resource/Sound/siren.mp3
  SecretAgent/SecretAgent/Global/Service/SoundManager.swift
Labels: Ꜣ Logic, 🌊 Miller
